"on":
  push:
      branches:
          - main
jobs:
  build_css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 10
          submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/repo-name/assets/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.3.9
        with:
          source: _scss/style.scss
          destination: /tmp/repo-name/assets/css/style.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Cherry-pick the latest commit from main
        run: git fetch origin main && git cherry-pick main
      
      - name: Remove old css files in gh-pages branch
        run: rm -rf css

      - name: Move compiled CSS to path within gh-pages branch
        run: mv /tmp/repo-name/assets/css css

      - name: Add and Commit changes to gh-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f .
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: gh-pages
